# Generated by Django 3.0.4 on 2020-03-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name_plural': 'Article',
            },
        ),
    ]
