# Generated by Django 3.0.4 on 2020-03-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.TextField(blank=True, null=True, verbose_name='writer'),
        ),
    ]
